### ISSUE TITLE
Remove superfluous custom bytecode listings from kube deployment scripts

### ISSUE THREAD

**Issue by sdorr0** [kentik/kentik-kube-deploy#15]
The current `kustomization-template.yml` file includes a kappa-config entry for custom bytecode:

```
configMapGenerator:
  - name: kappa-config
    literals:
      - capture=__CAPTURE__
      - device=__CLUSTER__
      - region=__REGION__
      - plan=__PLAN__
      - bytecode=x86_64/kappa_bpf-ubuntu-5.4.o
 ```

This bytecode option is largely superfluous at this point as, to date, no clients are running linux systems with old enough kernels to require custom bytecode and the likelihood of getting a new client with a pre-5.8 kernel is exceedingly unlikely, SE's have reported that this entry is a source of confusion for customers.

Let's remove this entry, test to make sure deploys are still functional without it, and update the `kentik-kube-deploy` repo.  In the unlikely event a customer requires it, SE's can instruct a client with the proper .yml config additions to include custom byte code.
